src/Vidly.Web/Controllers/CodeTablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.DataServices.DbContexts;

namespace Vidly.Web.Controllers
{
    public class CodeTablesController : Controller
    {
        private VidlyDbContext _context = new VidlyDbContext();
        // GET: CodeTables
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/Vidly.Web/Controllers/MovieGenreCodesController.cs
using System.Linq;
using System.Web.Mvc;
using Vidly.DataServices.DbContexts;

namespace Vidly.Web.Controllers
{
    public class MovieGenreCodesController : Controller
    {
        private readonly VidlyDbContext _context;

        public MovieGenreCodesController()
        {
            _context = new VidlyDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ViewResult Index()
        {
            var movieGenreCodes = _context.MovieGenreCodes.ToList();

            return View(movieGenreCodes);
        }

    }
}

src/Vidly.Web/Views/MovieGenreCodes/Index.cshtml
@model IEnumerable<Vidly.DataServices.Models.MovieGenreCode>
@{
    ViewBag.Title = "Movie Genre Codes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movie Genre Codes</h2>


<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(m => m.Id)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.IsActive)
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Id
            </td>
            <td>
                @item.Genre
            </td>
            <td>
                @item.IsActive
            </td>
        </tr>
    }
    </tbody>

</table>
<div>
    @Html.ActionLink("Back to Code Tables", "Index", "CodeTables")
</div>