src/Vidly.Web/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using Vidly.DataServices.DbContexts;
using Vidly.DataServices.Models;
using Vidly.DataServices.Services;
using Vidly.Web.ViewModels;

namespace Vidly.Web.Controllers
{
    public class RolesController : Controller
    {
        private VidlyIdentityDbContext _context;
        private ApplicationUserManager _userManager;
        private ApplicationRoleManager _roleManager;

        public RolesController()
        {
            _context = new VidlyIdentityDbContext();
        }

        public RolesController(ApplicationUserManager userManager,ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        
        public ApplicationUserManager UserManager
        {
            get => _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            set => _userManager = value;
        }

        
        public ApplicationRoleManager RoleManager
        {
            get => _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            private set => _roleManager = value;
        }

        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // Get the list of Users in this Role
            var users = new List<ApplicationUser>();

            // Get the list of Users in this Role
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }

            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return View(role);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(RoleEditViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = new ApplicationRole(roleViewModel.Name) {RoleDescription = roleViewModel.RoleDescription};
                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            RoleEditViewModel roleModel = new RoleEditViewModel
            {
                Id = role.Id,
                Name = role.Name,
                RoleDescription = role.RoleDescription
            };
            return View(roleModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Name,Id,RoleDescription")] RoleEditViewModel roleModel)
        {
            if (!ModelState.IsValid)
                return View();

            var role = await RoleManager.FindByIdAsync(roleModel.Id);
            role.Name = roleModel.Name;
            role.RoleDescription = roleModel.RoleDescription;
            await RoleManager.UpdateAsync(role);
            return RedirectToAction("Index");
        }
    }
}

src/Vidly.Web/Views/Roles/Create.cshtml
@model Vidly.Web.ViewModels.RoleEditViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create.</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Role.</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.RoleDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.RoleDescription, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoleDescription)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Vidly.Web/Views/Roles/Details.cshtml
@model Vidly.DataServices.Models.ApplicationRole

@{
    ViewBag.Title = "Details";
}

<h2>Role Details.</h2>

<div>
    <h4>Roles.</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
    </dl>    

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RoleDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RoleDescription)
        </dd>
    </dl>
</div>


<h4>List of users in this role</h4>
@if (ViewBag.UserCount == 0)
{
    <hr />
    <p>No users found in this role.</p>
}

<table class="table">

    @foreach (var item in ViewBag.Users)
    {
        <tr>
            <td>
                @item.UserName
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/Vidly.Web/Views/Roles/Edit.cshtml
@model Vidly.Web.ViewModels.RoleEditViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit Role</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Roles.</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.RoleDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.RoleDescription, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoleDescription)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Vidly.Web/Views/Roles/Index.cshtml
@model IEnumerable<Vidly.DataServices.Models.ApplicationRole>
@{
    ViewBag.Title = "Security Roles";
}

<h2>Security Roles</h2>
<p>
    @Html.ActionLink("New Role", "Create", "Roles", new { id = 0 }, new { @class = "btn btn-primary" })
</p>
<table class="table table-bordered table-hover" id="rolesTable">
    <thead>
    <tr>
        <th>@Html.DisplayNameFor(model => model.Id)</th>
        <th>@Html.DisplayNameFor(model => model.Name)</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var role in Model)
    {
        <tr>
            <td> @Html.DisplayFor(modelItem => role.Id) </td>
            <td> @Html.DisplayFor(modelItem => role.Name) </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id = role.Id}) |
                @Html.ActionLink("Details", "Details", new {id = role.Id}) 
            </td>
        </tr>
    }
    </tbody>
</table>

@section scripts
{
    <script>
        $(document).ready(function() {
            $('#rolesTable').DataTable();
        });
    </script>
}